### ISSUE TITLE
Prompt examples for make_img.ipynb

### ISSUE THREAD

**Issue by drphero** [mycfhs/DreamMix#2]
Could you please give us some examples of the prompts used here?

```
regular_prompts_list = [
    ...
]
```

**Comment by mycfhs** [comment]
Of cource! Here's the example via VLM:
![1595e538d5f475da455d607a0723672b](https://github.com/user-attachments/assets/faf9273d-bc23-4310-8fa0-c7a356a18e62)
![98dd800385bfe2f8dc30a0ebf7a0cf3b](https://github.com/user-attachments/assets/bfc95c0f-6ae3-4d44-8906-473699266e0b)

Also, to keep things simple, you can manual set prompt. For instance, if you want to edit "clay" attribute, just gengerate 
```
regular_prompts_list = [
    "a photo of a teapot",
    "a photo of a clay teapot"
]
```
and training use prompt  "a photo of a sks teapot",
infer with sks_decompose_words=["clay"]

**Comment by drphero** [comment]
Thanks for the info. I've completed that and have come across some issues when running train.py with the given command.

The first is in `--instance_data_dir="train_data/${CATEGORY}"/image`. After renaming the dataset directory from the dreambooth repo to train_data, the folder structure is for example train_data/teapot/00.jpg for the first image. After changing the line to `--instance_data_dir="train_data/${CATEGORY}"` it could find the images, but since I think it was also expecting masks, it ouput: 
```Processing image and mask to latent
Warning! mask of image train_data/teapot/00.jpg not exist! Ignore..
Warning! mask of image train_data/teapot/01.jpg not exist! Ignore..
Warning! mask of image train_data/teapot/02.jpg not exist! Ignore..
Warning! mask of image train_data/teapot/03.jpg not exist! Ignore..
Warning! mask of image train_data/teapot/04.jpg not exist! Ignore..
```
I think this caused this error:
```
Traceback (most recent call last):
  File "/workspace/DreamMix/train.py", line 2171, in <module>
    main(args)
  File "/workspace/DreamMix/train.py", line 1823, in main
    for step, batch in enumerate(train_dataloader):
  File "/root/micromamba/envs/DreamMix/lib/python3.10/site-packages/accelerate/data_loader.py", line 452, in __iter__
    current_batch = next(dataloader_iter)
  File "/root/micromamba/envs/DreamMix/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/root/micromamba/envs/DreamMix/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/root/micromamba/envs/DreamMix/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/micromamba/envs/DreamMix/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/workspace/DreamMix/train.py", line 1031, in __getitem__
    img_id = index % self.num_instance_images
ZeroDivisionError: integer division or modulo by zero
```

One other thing I noticed in `--instance_prompt="${INSTANCE_PROMPT]"` is that the ] should be } or it won't run at all.

**Comment by mycfhs** [comment]
Apologies for providing an incorrect dataset link earlier. Please access the instance dataset at [github.com/mycfhs/dreambooth_mask](https://github.com/mycfhs/dreambooth_mask). 
Thank you for pointing it out; the README has been updated accordingly.
