### ISSUE TITLE
你好，问下这个model文件在哪呢，还有就是必须要24g的gpu才可以吗，16g的老哥有没有试过

### ISSUE THREAD

**Issue by XM512** [mycfhs/DreamMix#3]

**Comment by mycfhs** [comment]
你好 XL模型文件用的https://huggingface.co/frankjoshua/juggernautXL_v8Rundiffusion, 无需手动下载, 其他模型见readme
由于模型需要在float32精度训练 精简以后24g显存已经是最低的程度了 :)

**Comment by XM512** [comment]
不好意思，我是说你给的这个代码程序中好像没有model文件啊，还有就是只进行推理的话16g可以吗

**Comment by mycfhs** [comment]
你好 模型文件具体指的什么呢？
只是infer的话足够了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: XM512 ***@***.***&gt;
发送时间: 2024年11月30日 18:46
收件人: mycfhs/DreamMix ***@***.***&gt;
抄送: YiCheng Yang ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [mycfhs/DreamMix] 你好，问下这个model文件在哪呢，还有就是必须要24g的gpu才可以吗，16g的老哥有没有试过 (Issue #3)





 
不好意思，我是说你给的这个代码程序中好像没有model文件啊，还有就是只进行推理的话16g可以吗

**Comment by XM512** [comment]
就是没有model这个文件夹，还有就是我没看懂推理的过程中为啥只输入一个原始图像和对应的掩码以及文本，不是说还有另一个图像作为参考吗？

**Comment by mycfhs** [comment]
oh 确实, 因为文件夹是空的就没传上去, 现在加上了.
我们的方法是微调一个lora来学习ref img的特征,而不是在infer的时候添加ref image, 所以需要训练一个lora.
