### ISSUE TITLE
inference

### ISSUE THREAD

**Issue by xianluom** [mycfhs/DreamMix#4]
Could you provide a Lora model for the inference process? I have tried several Lora models, but none of them are suitable.

**Comment by mycfhs** [comment]
Any issues during training? Apologies for not having a trained LoRA available.

**Comment by xianluom** [comment]
I did not use training, the Lora issue occurred during inference.

**Comment by mycfhs** [comment]
Got it. This bug have fixed just now for no lora inference. Also, you can download lora file here [https://huggingface.co/metercai/SimpleSDXL/blob/main/loras/sd_xl_offset_example-lora_1.0.safetensors](url)
and set lora config in code
```
lora_config = [
    {
        "model_path": "./models/lora/sd_xl_offset_example-lora_1.0.safetensors",
        "scale": 0.1,  # from 0.1 to 0.5
        "for_raw_unet": True,
        "for_fooocus_unet": True,
    }
]
```

**Comment by xianluom** [comment]
ok thanks

**Comment by mycfhs** [comment]
: )
